// The full country picker: every country the client's world map can select,
// each backed by a real ISO 3166-1 alpha-2 code (used for Google News'
// gl/ceid params) and a primary language (Google News' hl param). `mapName`
// is the exact string used by the world-atlas/Natural-Earth topojson the
// client's map renders — kept alongside `name` (the cleaner display name)
// so the two never drift apart silently.

export interface Country {
  code: string; // ISO 3166-1 alpha-2
  name: string;
  mapName: string; // matches world-atlas topojson properties.name exactly
  language: string; // Google News `hl` code
}

export const COUNTRIES: Country[] = [
  { code: "MA", name: "Morocco", mapName: "Morocco", language: "ar" },
  { code: "DZ", name: "Algeria", mapName: "Algeria", language: "ar" },
  { code: "TN", name: "Tunisia", mapName: "Tunisia", language: "ar" },
  { code: "LY", name: "Libya", mapName: "Libya", language: "ar" },
  { code: "EG", name: "Egypt", mapName: "Egypt", language: "ar" },
  { code: "MR", name: "Mauritania", mapName: "Mauritania", language: "ar" },
  { code: "EH", name: "Western Sahara", mapName: "W. Sahara", language: "ar" },
  { code: "SA", name: "Saudi Arabia", mapName: "Saudi Arabia", language: "ar" },
  { code: "AE", name: "United Arab Emirates", mapName: "United Arab Emirates", language: "ar" },
  { code: "QA", name: "Qatar", mapName: "Qatar", language: "ar" },
  { code: "KW", name: "Kuwait", mapName: "Kuwait", language: "ar" },
  { code: "OM", name: "Oman", mapName: "Oman", language: "ar" },
  { code: "JO", name: "Jordan", mapName: "Jordan", language: "ar" },
  { code: "LB", name: "Lebanon", mapName: "Lebanon", language: "ar" },
  { code: "SY", name: "Syria", mapName: "Syria", language: "ar" },
  { code: "IQ", name: "Iraq", mapName: "Iraq", language: "ar" },
  { code: "YE", name: "Yemen", mapName: "Yemen", language: "ar" },
  { code: "PS", name: "Palestine", mapName: "Palestine", language: "ar" },
  { code: "SD", name: "Sudan", mapName: "Sudan", language: "ar" },
  { code: "SS", name: "South Sudan", mapName: "S. Sudan", language: "en" },
  { code: "SO", name: "Somalia", mapName: "Somalia", language: "en" },
  { code: "DJ", name: "Djibouti", mapName: "Djibouti", language: "fr" },
  { code: "IR", name: "Iran", mapName: "Iran", language: "fa" },
  { code: "TR", name: "Turkey", mapName: "Turkey", language: "tr" },
  { code: "IL", name: "Israel", mapName: "Israel", language: "he" },
  { code: "CY", name: "Cyprus", mapName: "Cyprus", language: "en" },

  { code: "FR", name: "France", mapName: "France", language: "fr" },
  { code: "ES", name: "Spain", mapName: "Spain", language: "es" },
  { code: "PT", name: "Portugal", mapName: "Portugal", language: "pt" },
  { code: "GB", name: "United Kingdom", mapName: "United Kingdom", language: "en" },
  { code: "IE", name: "Ireland", mapName: "Ireland", language: "en" },
  { code: "DE", name: "Germany", mapName: "Germany", language: "de" },
  { code: "IT", name: "Italy", mapName: "Italy", language: "it" },
  { code: "NL", name: "Netherlands", mapName: "Netherlands", language: "nl" },
  { code: "BE", name: "Belgium", mapName: "Belgium", language: "fr" },
  { code: "LU", name: "Luxembourg", mapName: "Luxembourg", language: "fr" },
  { code: "CH", name: "Switzerland", mapName: "Switzerland", language: "de" },
  { code: "AT", name: "Austria", mapName: "Austria", language: "de" },
  { code: "DK", name: "Denmark", mapName: "Denmark", language: "da" },
  { code: "SE", name: "Sweden", mapName: "Sweden", language: "sv" },
  { code: "NO", name: "Norway", mapName: "Norway", language: "no" },
  { code: "FI", name: "Finland", mapName: "Finland", language: "fi" },
  { code: "IS", name: "Iceland", mapName: "Iceland", language: "en" },
  { code: "GR", name: "Greece", mapName: "Greece", language: "el" },
  { code: "PL", name: "Poland", mapName: "Poland", language: "pl" },
  { code: "CZ", name: "Czechia", mapName: "Czechia", language: "cs" },
  { code: "SK", name: "Slovakia", mapName: "Slovakia", language: "sk" },
  { code: "HU", name: "Hungary", mapName: "Hungary", language: "hu" },
  { code: "RO", name: "Romania", mapName: "Romania", language: "ro" },
  { code: "BG", name: "Bulgaria", mapName: "Bulgaria", language: "bg" },
  { code: "HR", name: "Croatia", mapName: "Croatia", language: "hr" },
  { code: "SI", name: "Slovenia", mapName: "Slovenia", language: "sl" },
  { code: "RS", name: "Serbia", mapName: "Serbia", language: "sr" },
  { code: "BA", name: "Bosnia and Herzegovina", mapName: "Bosnia and Herz.", language: "bs" },
  { code: "ME", name: "Montenegro", mapName: "Montenegro", language: "en" },
  { code: "MK", name: "North Macedonia", mapName: "Macedonia", language: "en" },
  { code: "AL", name: "Albania", mapName: "Albania", language: "sq" },
  { code: "XK", name: "Kosovo", mapName: "Kosovo", language: "en" },
  { code: "EE", name: "Estonia", mapName: "Estonia", language: "et" },
  { code: "LV", name: "Latvia", mapName: "Latvia", language: "lv" },
  { code: "LT", name: "Lithuania", mapName: "Lithuania", language: "lt" },
  { code: "UA", name: "Ukraine", mapName: "Ukraine", language: "uk" },
  { code: "BY", name: "Belarus", mapName: "Belarus", language: "ru" },
  { code: "MD", name: "Moldova", mapName: "Moldova", language: "ro" },
  { code: "RU", name: "Russia", mapName: "Russia", language: "ru" },
  { code: "GE", name: "Georgia", mapName: "Georgia", language: "en" },
  { code: "AM", name: "Armenia", mapName: "Armenia", language: "en" },
  { code: "AZ", name: "Azerbaijan", mapName: "Azerbaijan", language: "en" },

  { code: "US", name: "United States", mapName: "United States of America", language: "en" },
  { code: "CA", name: "Canada", mapName: "Canada", language: "en" },
  { code: "MX", name: "Mexico", mapName: "Mexico", language: "es" },
  { code: "GT", name: "Guatemala", mapName: "Guatemala", language: "es" },
  { code: "BZ", name: "Belize", mapName: "Belize", language: "en" },
  { code: "HN", name: "Honduras", mapName: "Honduras", language: "es" },
  { code: "SV", name: "El Salvador", mapName: "El Salvador", language: "es" },
  { code: "NI", name: "Nicaragua", mapName: "Nicaragua", language: "es" },
  { code: "CR", name: "Costa Rica", mapName: "Costa Rica", language: "es" },
  { code: "PA", name: "Panama", mapName: "Panama", language: "es" },
  { code: "CU", name: "Cuba", mapName: "Cuba", language: "es" },
  { code: "JM", name: "Jamaica", mapName: "Jamaica", language: "en" },
  { code: "HT", name: "Haiti", mapName: "Haiti", language: "fr" },
  { code: "DO", name: "Dominican Republic", mapName: "Dominican Rep.", language: "es" },
  { code: "TT", name: "Trinidad and Tobago", mapName: "Trinidad and Tobago", language: "en" },
  { code: "PR", name: "Puerto Rico", mapName: "Puerto Rico", language: "es" },
  { code: "BS", name: "Bahamas", mapName: "Bahamas", language: "en" },

  { code: "BR", name: "Brazil", mapName: "Brazil", language: "pt" },
  { code: "AR", name: "Argentina", mapName: "Argentina", language: "es" },
  { code: "CL", name: "Chile", mapName: "Chile", language: "es" },
  { code: "CO", name: "Colombia", mapName: "Colombia", language: "es" },
  { code: "PE", name: "Peru", mapName: "Peru", language: "es" },
  { code: "VE", name: "Venezuela", mapName: "Venezuela", language: "es" },
  { code: "EC", name: "Ecuador", mapName: "Ecuador", language: "es" },
  { code: "BO", name: "Bolivia", mapName: "Bolivia", language: "es" },
  { code: "PY", name: "Paraguay", mapName: "Paraguay", language: "es" },
  { code: "UY", name: "Uruguay", mapName: "Uruguay", language: "es" },
  { code: "GY", name: "Guyana", mapName: "Guyana", language: "en" },
  { code: "SR", name: "Suriname", mapName: "Suriname", language: "nl" },

  { code: "NG", name: "Nigeria", mapName: "Nigeria", language: "en" },
  { code: "GH", name: "Ghana", mapName: "Ghana", language: "en" },
  { code: "CI", name: "Côte d'Ivoire", mapName: "Côte d'Ivoire", language: "fr" },
  { code: "SN", name: "Senegal", mapName: "Senegal", language: "fr" },
  { code: "ML", name: "Mali", mapName: "Mali", language: "fr" },
  { code: "BF", name: "Burkina Faso", mapName: "Burkina Faso", language: "fr" },
  { code: "NE", name: "Niger", mapName: "Niger", language: "fr" },
  { code: "TD", name: "Chad", mapName: "Chad", language: "fr" },
  { code: "GN", name: "Guinea", mapName: "Guinea", language: "fr" },
  { code: "GW", name: "Guinea-Bissau", mapName: "Guinea-Bissau", language: "pt" },
  { code: "GM", name: "Gambia", mapName: "Gambia", language: "en" },
  { code: "SL", name: "Sierra Leone", mapName: "Sierra Leone", language: "en" },
  { code: "LR", name: "Liberia", mapName: "Liberia", language: "en" },
  { code: "TG", name: "Togo", mapName: "Togo", language: "fr" },
  { code: "BJ", name: "Benin", mapName: "Benin", language: "fr" },
  { code: "CM", name: "Cameroon", mapName: "Cameroon", language: "fr" },
  { code: "GA", name: "Gabon", mapName: "Gabon", language: "fr" },
  { code: "CG", name: "Congo", mapName: "Congo", language: "fr" },
  { code: "CD", name: "DR Congo", mapName: "Dem. Rep. Congo", language: "fr" },
  { code: "CF", name: "Central African Republic", mapName: "Central African Rep.", language: "fr" },
  { code: "GQ", name: "Equatorial Guinea", mapName: "Eq. Guinea", language: "es" },
  { code: "AO", name: "Angola", mapName: "Angola", language: "pt" },
  { code: "ZM", name: "Zambia", mapName: "Zambia", language: "en" },
  { code: "ZW", name: "Zimbabwe", mapName: "Zimbabwe", language: "en" },
  { code: "MW", name: "Malawi", mapName: "Malawi", language: "en" },
  { code: "MZ", name: "Mozambique", mapName: "Mozambique", language: "pt" },
  { code: "TZ", name: "Tanzania", mapName: "Tanzania", language: "en" },
  { code: "KE", name: "Kenya", mapName: "Kenya", language: "en" },
  { code: "UG", name: "Uganda", mapName: "Uganda", language: "en" },
  { code: "RW", name: "Rwanda", mapName: "Rwanda", language: "fr" },
  { code: "BI", name: "Burundi", mapName: "Burundi", language: "fr" },
  { code: "ET", name: "Ethiopia", mapName: "Ethiopia", language: "en" },
  { code: "ER", name: "Eritrea", mapName: "Eritrea", language: "en" },
  { code: "ZA", name: "South Africa", mapName: "South Africa", language: "en" },
  { code: "NA", name: "Namibia", mapName: "Namibia", language: "en" },
  { code: "BW", name: "Botswana", mapName: "Botswana", language: "en" },
  { code: "LS", name: "Lesotho", mapName: "Lesotho", language: "en" },
  { code: "SZ", name: "Eswatini", mapName: "eSwatini", language: "en" },
  { code: "MG", name: "Madagascar", mapName: "Madagascar", language: "fr" },

  { code: "CN", name: "China", mapName: "China", language: "zh-CN" },
  { code: "JP", name: "Japan", mapName: "Japan", language: "ja" },
  { code: "KR", name: "South Korea", mapName: "South Korea", language: "ko" },
  { code: "KP", name: "North Korea", mapName: "North Korea", language: "en" },
  { code: "TW", name: "Taiwan", mapName: "Taiwan", language: "zh-TW" },
  { code: "MN", name: "Mongolia", mapName: "Mongolia", language: "en" },
  { code: "IN", name: "India", mapName: "India", language: "en" },
  { code: "PK", name: "Pakistan", mapName: "Pakistan", language: "en" },
  { code: "BD", name: "Bangladesh", mapName: "Bangladesh", language: "bn" },
  { code: "LK", name: "Sri Lanka", mapName: "Sri Lanka", language: "en" },
  { code: "NP", name: "Nepal", mapName: "Nepal", language: "en" },
  { code: "BT", name: "Bhutan", mapName: "Bhutan", language: "en" },
  { code: "MM", name: "Myanmar", mapName: "Myanmar", language: "en" },
  { code: "TH", name: "Thailand", mapName: "Thailand", language: "th" },
  { code: "LA", name: "Laos", mapName: "Laos", language: "en" },
  { code: "KH", name: "Cambodia", mapName: "Cambodia", language: "en" },
  { code: "VN", name: "Vietnam", mapName: "Vietnam", language: "vi" },
  { code: "MY", name: "Malaysia", mapName: "Malaysia", language: "en" },
  { code: "SG", name: "Singapore", mapName: "Singapore", language: "en" },
  { code: "ID", name: "Indonesia", mapName: "Indonesia", language: "id" },
  { code: "PH", name: "Philippines", mapName: "Philippines", language: "en" },
  { code: "TL", name: "Timor-Leste", mapName: "Timor-Leste", language: "pt" },
  { code: "BN", name: "Brunei", mapName: "Brunei", language: "en" },
  { code: "AF", name: "Afghanistan", mapName: "Afghanistan", language: "en" },
  { code: "KZ", name: "Kazakhstan", mapName: "Kazakhstan", language: "ru" },
  { code: "UZ", name: "Uzbekistan", mapName: "Uzbekistan", language: "ru" },
  { code: "TM", name: "Turkmenistan", mapName: "Turkmenistan", language: "ru" },
  { code: "TJ", name: "Tajikistan", mapName: "Tajikistan", language: "ru" },
  { code: "KG", name: "Kyrgyzstan", mapName: "Kyrgyzstan", language: "ru" },

  { code: "AU", name: "Australia", mapName: "Australia", language: "en" },
  { code: "NZ", name: "New Zealand", mapName: "New Zealand", language: "en" },
  { code: "PG", name: "Papua New Guinea", mapName: "Papua New Guinea", language: "en" },
  { code: "FJ", name: "Fiji", mapName: "Fiji", language: "en" },
  { code: "SB", name: "Solomon Islands", mapName: "Solomon Is.", language: "en" },
  { code: "VU", name: "Vanuatu", mapName: "Vanuatu", language: "en" },
  { code: "NC", name: "New Caledonia", mapName: "New Caledonia", language: "fr" },
  { code: "GL", name: "Greenland", mapName: "Greenland", language: "da" },
  { code: "FK", name: "Falkland Islands", mapName: "Falkland Is.", language: "en" },
];

export function getCountry(code: string): Country | undefined {
  return COUNTRIES.find((c) => c.code.toLowerCase() === code.toLowerCase());
}

export function findCountryByMapName(mapName: string): Country | undefined {
  return COUNTRIES.find((c) => c.mapName.toLowerCase() === mapName.toLowerCase());
}
